CREATE TABLE company
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    title VARCHAR(64),
    date  DATE,
    cost  FLOAT
);

CREATE TABLE project
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    title VARCHAR(64),
    cost  FLOAT
);

CREATE TABLE company_project
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    company_id BIGINT                                              NOT NULL,
    project_id BIGINT                                              NOT NULL,
    FOREIGN KEY (company_id) REFERENCES company,
    FOREIGN KEY (project_id) REFERENCES project
);

CREATE TABLE car
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    model           VARCHAR(32),
    engine_capacity FLOAT,
    mileage         BIGINT,
    employee        BIGINT,
    FOREIGN KEY (employee) REFERENCES employee
);

CREATE TABLE employee
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name            VARCHAR(32),
    age             INT,
    car             BIGINT                                              NOT NULL,
    additional_info JSONB,
    FOREIGN KEY (car) REFERENCES car
);

CREATE TABLE project_employee
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    project_id  BIGINT                                              NOT NULL,
    employee_id BIGINT                                              NOT NULL,
    FOREIGN KEY (project_id) REFERENCES project,
    FOREIGN KEY (employee_id) REFERENCES employee
);